exclude: '^(.*egg.info.*|docs/.*)'
repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
        -   id: pyupgrade
            args: [--py38-plus]
-   repo: https://github.com/PyCQA/isort  # config: .isort.cfg
    rev: 5.12.0
    hooks:
      - id: isort
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --safe
          - --line-length=120
        language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: check-ast
-   repo: https://github.com/PyCQA/flake8  # config: .flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear == 20.11.1
          - flake8-init-return == 1.0.0
