name: Snowflake Mlflow Plugin
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --files ${{ steps.changed-files.outputs.all_changed_files }}

  test:
    name: Test ${{ matrix.os.download_name }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - image_name: ubuntu-latest
            download_name: linux
          - image_name: macos-latest
            download_name: macos
          - image_name: windows-latest
            download_name: windows
    runs-on: ${{ matrix.os.image_name }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev_requirements.txt
    - name: Install package from source
      run: |
        python -m pip install -e . --verbose
    - name: Test with python
      run: |
        pytest tests/
